---
- name: Install and start apache server
  hosts: prod
  tasks:
    - name: http is present
      yum:
        name: httpd
        state: present
    - name: index.html is present
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true

